# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-18.04"
  config.vm.network "private_network", ip: "192.168.33.10"
  config.vm.synced_folder "../..", "/vagrant"

  config.vm.network :forwarded_port, host: 80, guest: 80
  config.vm.network :forwarded_port, host: 5432, guest: 5432

  config.vm.provider "virtualbox" do |vb|
    vb.name = "micro_erp"
    vb.memory = "2048"
    vb.cpus = "2"
  end

  config.vm.provision "shell" do |s|
    s.binary = true
    s.inline = <<-SHELL
      apt-get update
      apt-get install apt-transport-https ca-certificates curl software-properties-common
      curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
      add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
      apt-get update
      apt-get install -y docker-ce
      sudo usermod -aG docker vagrant
      sudo wget https://github.com/qmu/mcc/releases/download/v0.9.6/linux_amd64_mcc -O /usr/local/bin/mcc
      sudo chmod +x /usr/local/bin/mcc
      sudo curl -L "https://github.com/docker/compose/releases/download/1.23.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
      sudo chmod +x /usr/local/bin/docker-compose
    SHELL
  end
end